In [9]:
import tensorflow as tf
import numpy as np

n_inputs = 3
n_step = 2
n_neurons = 5

#X0 = tf.placeholder(tf.float32, [None, n_inputs])
#X1 = tf.placeholder(tf.float32, [None, n_inputs])

#basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
#output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1], dtype=tf.float32)
#Y0, Y1 = output_seqs

XX = tf.placeholder(tf.float32, None)

Xa = XX -1
with tf.Session() as session:
    cc = session.run(Xa, feed_dict={XX: -10.0})
    print(cc)

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    bb = session.run(Xa, feed_dict={XX:5})
    print(result)
    #print(cc)


-11.0
[ 2.  4.  6.]


In [14]:
X_batch = np.array([[[0, 1, 2], [9, 8, 7]],
                   [[3, 4, 5], [0, 0, 0]],
                   [[6, 7, 8], [6, 5, 4]],
                   [[9, 0, 1], [3, 2, 1]]])

In [15]:
#print(Y1_val)

X = tf.placeholder(tf.float32, [None, n_step, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0, 2]))

with tf.Session() as sess:
  sess.run(X_seqs, feed_dict={X:X_batch})

In [23]:

def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)
    
reset_graph()

n_step = 2
n_inputs = 3
n_neurons = 5

#init = tf.global_variables_initializer()
X = tf.placeholder(tf.float32, [None, n_step, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0, 2]))
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)
outputs = tf.transpose(tf.stack(output_seqs), perm=[1, 0, 2])

init = tf.global_variables_initializer()
X_batch = np.array([[[0, 1, 2], [9, 8, 7]],
                   [[3, 4, 5], [0, 0, 0]],
                   [[6, 7, 8], [6, 5, 4]],
                   [[9, 0, 1], [3, 2, 1]]])
with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X:X_batch})

    print(outputs_val)

[[[-0.91279727  0.83698678 -0.89277941  0.80308062 -0.5283336 ]
  [-1.          1.         -0.99794829  0.99985468 -0.99273592]]

 [[-0.99994391  0.99951613 -0.9946925   0.99030769 -0.94413054]
  [ 0.48733309  0.93389565 -0.31362072  0.88573611  0.2424476 ]]

 [[-1.          0.99999875 -0.99975014  0.99956584 -0.99466234]
  [-0.99994856  0.99999434 -0.96058172  0.99784708 -0.9099462 ]]

 [[-0.95972425  0.99951482  0.96938795 -0.969908   -0.67668229]
  [-0.84596014  0.96288228  0.96856463 -0.14777924 -0.9119423 ]]]
